GoldenIdea/urls.py
import os
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.urls import path
from django.conf.urls.static import static
from ideas.views import list_view

urlpatterns = [
    path('', list_view, name='list'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('ideas/', include('ideas.urls', namespace='ideas')),
    path('activities/', include('activities.urls', namespace='activities')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.LOGS_URL, document_root=settings.LOGS_DIR)
    LETSENCRYPTIT_URL = '/.well-known/'
    LETSENCRYPTIT_ROOT = os.path.join(settings.BASE_DIR, ".well-known")
    urlpatterns += static(LETSENCRYPTIT_URL, document_root=LETSENCRYPTIT_ROOT)

accounts/urls.py
from django.conf.urls import url
from . import views


app_name = 'accounts.views'


urlpatterns = [
    url(r'^login/$',
        views.login_view,
        name='login'),
    url(r'^ajax_login/$',
        views.ajax_login_view,
        name='ajax-login'),
    url(r'^logout/$',
        views.logout_view,
        name='logout'),
    url(r'^change_password/$',
        views.change_password_view,
        name='change-password'),
]

ideas/urls.py
from django.conf.urls import url
from . import views


app_name = 'ideas.views'


urlpatterns = [
    url(r'^list/$',
        views.list_view,
        name='list'),
    url(r'^detail/(?P<idea_id>[0-9]+)/$',
        views.detail_view,
        name='detail'),
    url(r'^create/$',
        views.create_view,
        name='create'),
    url(r'^edit/$',
        views.edit_view,
        name='edit'),
    url(r'^export/$',
        views.export_view,
        name='export'),
    url(r'^accept/(?P<idea_id>[0-9]+)/$',
        views.accept_view,
        name='accept'),
]

common/models.py
from django.db import models
from django.utils import timezone


class BaseModel(models.Model):
    created_datetime = models.DateTimeField(auto_now_add=True)
    modified_datetime = models.DateTimeField("last modified datetime", blank=True)

    def save(self, *args, **kwargs):
        if not kwargs.pop('skip_modified_datetime', False):
            self.modified_datetime = timezone.now()
        super(BaseModel, self).save(*args, **kwargs)

    class Meta:
        abstract = True

common/views.py
from django.shortcuts import render

# Create your views here.

common/templates/common/base.html
{% load static %}
<!DOCTYPE html>
<html class="has-navbar-fixed-top">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=0">
    <title>
    {% block title %}
    {% endblock %}
    </title>
    <script src="{% static "common/js/jquery.min.js" %}"></script>
    <script src="{% static "common/js/bulma-toast.min.js" %}"></script>
    <script src="{% static "common/js/base.js" %}"></script>
    <link rel="stylesheet" href="{% static "common/css/font-awesome.min.css" %}" />
    <link rel="stylesheet" href="{% static "common/css/bulma.min.css" %}" />
    <link rel="stylesheet" href="{% static "common/css/base.css" %}" />
    {% block static %}
    {% endblock %}
  </head>
  <body>
    <nav
      class="navbar is-white is-fixed-top topNav"
      role="navigation"
      aria-label="main navigation"
    >
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item" href="/">
            <img src="{% static "common/img/evercan-logo.png" %}" />
          </a>

          <a role="button" class="navbar-burger burger" data-target="navbar-content" aria-label="menu" aria-expanded="false">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>

        <div id="navbar-content" class="navbar-menu">
          <div class="navbar-start">
            <a
              class="navbar-item {% if 'ideas' in request.path or request.path == '/' %}is-active{% endif %}"
              href="{% url 'ideas:list' %}"
            >
              金点子
            </a>
            <a
              class="navbar-item {% if 'activities' in request.path %}is-active{% endif %}"
              href="{% url 'activities:list' %}"
            >
              投票
            </a>
          </div>
          <div class="navbar-end">
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                <span class="icon is-small">
                  <i class="fa fa-user-o"></i>
                </span>
                &nbsp;&nbsp;{{request.user.name}}
              </a>

              <div class="navbar-dropdown">
                <a id="change-password" class="navbar-item">
                  <span class="icon is-small">
                    <i class="fa fa-key"></i>
                  </span>
                  &nbsp;&nbsp;修改密码
                </a>
                <hr class="navbar-divider">
                <a class="navbar-item" href="{% url 'accounts:logout' %}">
                  <span class="icon is-small">
                    <i class="fa fa-power-off"></i>
                  </span>
                  &nbsp;&nbsp;退出登录
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <div id="change-password-modal" class="modal">
      <div class="modal-background"></div>
      <div class="modal-card">
        <header class="modal-card-head">
          <p class="modal-card-title has-text-centered">修改密码</p>
        </header>
        <section class="modal-card-body">
          <form>
            {% csrf_token %}
            <div class="field is-horizontal">
              <div class="field-label is-normal">
                <label class="label">新密码</label>
              </div>
              <div class="field-body">
                <div class="field">
                  <p class="control">
                    <input
                      id="password"
                      name="password"
                      class="input"
                      type="password"
                    />
                  </p>
                  <p id="password-help" class="help is-danger hidden"></p>
                </div>
              </div>
            </div>
            <div class="field is-horizontal">
              <div class="field-label is-normal">
                <label class="label">密码确认</label>
              </div>
              <div class="field-body">
                <div class="field">
                  <p class="control">
                    <input
                      id="password-repeat"
                      name="password-repeat"
                      class="input"
                      type="password"
                    />
                  </p>
                  <p id="password-repeat-help" class="help is-danger hidden"></p>
                </div>
              </div>
            </div>
          </form>
        </section>
        <footer class="modal-card-foot">
          <button id="submit" class="button is-success">提交</button>
          <button id="cancel-change-password" class="button">取消</button>
        </footer>
      </div>
    </div>
    {% block content %}
    {% endblock %}
  </body>
</html>