activities/urls.py
from django.conf.urls import url
from . import views


app_name = 'activities.views'


urlpatterns = [
    url(r'^list/$',
        views.list_view,
        name='list'),
    url(r'^detail/(?P<activity_id>[0-9]+)/$',
        views.detail_view,
        name='detail'),
    url(r'^create/$',
        views.create_view,
        name='create'),
    url(r'^vote/$',
        views.vote_view,
        name='vote'),
    url(r'^edit/$',
        views.edit_view,
        name='edit'),
]

ideas/urls.py
from django.conf.urls import url
from . import views


app_name = 'ideas.views'


urlpatterns = [
    url(r'^list/$',
        views.list_view,
        name='list'),
    url(r'^detail/(?P<idea_id>[0-9]+)/$',
        views.detail_view,
        name='detail'),
    url(r'^create/$',
        views.create_view,
        name='create'),
    url(r'^edit/$',
        views.edit_view,
        name='edit'),
    url(r'^export/$',
        views.export_view,
        name='export'),
    url(r'^accept/(?P<idea_id>[0-9]+)/$',
        views.accept_view,
        name='accept'),
]

activities/models.py
from django.db import models
from django.db.models import Count, Max
from django.utils import timezone
from common.models import BaseModel
from common.debug_utils import debug


class Activity(BaseModel):
    STATUSES = (
        (0, '进行中'),
        (1, '已结束')
    )

    title = models.CharField(max_length=256)
    sponsor = models.ForeignKey(
        'accounts.User',
        on_delete=models.CASCADE,
    )
    end_datetime = models.DateTimeField(blank=True, null=True)
    status = models.IntegerField(default=0, choices=STATUSES)
    vote_num_per_user = models.IntegerField(default=8)

    @property
    def is_finished(self):
        return self.status == 1 or timezone.now() > self.end_datetime

    @property
    def option_max_vote_num(self):
        return self.option_set \
                   .all() \
                   .annotate(vote_num=Count('vote')) \
                   .aggregate(Max('vote_num'))['vote_num__max']

    @property
    def voted_users(self):
        return Vote.objects \
                   .filter(option__in=self.option_set.all()) \
                   .values_list('voter', flat=True)

    @property
    def vote_done_users(self):
        return Vote.objects \
                   .filter(option__in=self.option_set.all()) \
                   .values('voter') \
                   .annotate(voter_count=Count('voter')) \
                   .filter(voter_count__gte=self.vote_num_per_user) \
                   .values_list('voter', flat=True)

    def get_ordered_options(self):
        return self.option_set \
                   .all() \
                   .annotate(vote_num=Count('vote')) \
                   .order_by('-vote_num', 'id')

    def get_remaining_vote_num(self, user):
        voted_count = user.vote_set \
                          .filter(option__activity=self.id) \
                          .count()
        remaining_vote_num = self.vote_num_per_user - voted_count
        return remaining_vote_num

    def __str__(self):
        return self.title


class Option(BaseModel):
    activity = models.ForeignKey(
        'activities.Activity',
        on_delete=models.CASCADE,
    )
    content = models.CharField(
        blank=True,
        null=True,
        max_length=256
    )
    image = models.FileField(
        blank=True,
        null=True,
        upload_to='options/%Y/%m/%d'
    )

    @property
    def is_won(self):
        debug(self.activity.option_max_vote_num)
        return self.vote_set.count() == self.activity.option_max_vote_num

    def get_voters(self):
        return self.vote_set.all().values_list('voter', flat=True)

    def __str__(self):
        return self.content


class Vote(BaseModel):
    option = models.ForeignKey(
        'activities.Option',
        on_delete=models.CASCADE,
    )
    voter = models.ForeignKey(
        'accounts.User',
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.option.content + ' ' + self.voter.username

activities/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from activities.models import Activity, Option, Vote
from common.views_utils import json_response
from common.debug_utils import debug


@login_required(login_url='/accounts/login')
def list_view(request):
    activity_list = Activity.objects.filter(
        end_datetime__gte=timezone.now())

    status = request.GET.get('status', '0')
    if status == '1':
        activity_list = Activity.objects.filter(
            end_datetime__lt=timezone.now())

    paginator = Paginator(activity_list, 9)

    page = request.GET.get('page', 1)
    activities = paginator.get_page(page)

    return render(
        request,
        'activities/list.html',
        {'activities': activities})


@login_required(login_url='/accounts/login')
def detail_view(request, activity_id):
    activity = get_object_or_404(Activity, pk=activity_id)
    remaining_vote_num = activity.get_remaining_vote_num(request.user)
    options = activity.option_set.all()
    if activity.is_finished:
        options = activity.get_ordered_options()

    return render(
        request, 'activities/detail.html',
        {'activity': activity,
         'options': options,
         'remaining_vote_num': remaining_vote_num})


@login_required(login_url='/accounts/login')
def vote_view(request):
    activity_id = request.POST.get('activity_id', None)
    activity = get_object_or_404(Activity, pk=activity_id)
    user = request.user
    option_id_list = request.POST.getlist('option_id', [])
    if (not activity.is_finished and not activity.get_remaining_vote_num(user) < len(option_id_list)):
        for option_id in option_id_list:
            option = get_object_or_404(Option, pk=option_id)
            vote = Vote()
            vote.option = option
            vote.voter = user
            vote.save()

    return redirect('/activities/detail/%s/' % activity_id)


@login_required(login_url='/accounts/login')
def create_view(request):
    if not request.user.can_create_vote:
        return redirect('/activities/list/')

    if request.POST:
        activity = Activity()
        activity.title = request.POST.get('title', '')
        activity.vote_num_per_user = request.POST.get('vote_num_per_user', 8)
        activity.sponsor = request.user
        activity.end_datetime = request.POST.get('end_datetime', None)
        activity.save()

        images = request.FILES.getlist('option_image', [])
        contents = request.POST.getlist('option_content', [])
        for image, content in zip(images, contents):
            option = Option()
            option.image = image
            option.content = content
            option.activity = activity
            option.save()

        return redirect('/activities/detail/%s/' % activity.id)
    else:
        return render(request, 'activities/create.html')


@login_required(login_url='/accounts/login')
def edit_view(request):
    return json_response({'is_success': True})

activities/templates/activities/create.html
{% extends 'common/base.html' %}

{% load static %}
{% block title %}
发起投票
{% endblock %}
{% block static %}
<link rel="stylesheet" href="{% static "common/css/bulma-calendar.min.css" %}" />
<link rel="stylesheet" href="{% static "activities/css/common.css" %}" />
<link rel="stylesheet" href="{% static "activities/css/create.css" %}" />
<script src="{% static "common/js/bulma-calendar.min.js" %}"></script>
<script src="{% static "activities/js/common.js" %}"></script>
<script src="{% static "activities/js/create.js" %}"></script>
{% endblock %}

{% block content %}
<section class="container">
  <nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'activities:list' %}">投票</a></li>
      <li class="is-active"><a href="#" aria-current="page">发起投票</a></li>
    </ul>
  </nav>
  <form class="activity-form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="field">
      <label class="label">主题</label>
      <div class="control">
        <input class="input" name="title">
      </div>
      <p id="title-help" class="help is-danger hidden"></p>
    </div>

    <div class="columns">
      <div class="column is-one-third">
        <div class="field">
          <label class="label">截止时间</label>
          <div class="control">
            <input name="end_datetime" type="date" />
            <p id="end-datetime-help" class="help is-danger hidden"></p>
          </div>
        </div>
      </div>
      <div class="column is-one-third">
        <div class="field">
          <label class="label">每位投票者最多可投</label>
          <div class="control">
            <div class="select">
              <select name="vote_num_per_user">
                <option value="1">1票</option>
                <option value="2">2票</option>
                <option value="3">3票</option>
                <option value="4">4票</option>
                <option value="5">5票</option>
                <option value="6">6票</option>
                <option value="7">7票</option>
                <option value="8" selected>8票</option>
                <option value="9">9票</option>
                <option value="10">10票</option>
              </select>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div>
      <label class="label">
        选项
        <span class="icon add-option-icon" title="增加选项">
          <i class="fa fa-plus fa-fw" aria-hidden="true"></i>
        </span>        
      </label>
      <div class="columns is-multiline option-container"></div>
    </div>

    <div class="field is-grouped is-justified-center button-box">
      <div class="control">
        <button class="button is-link">发起投票</button>
      </div>
      <div class="control">
        <a
          type="button"
          class="button is-link is-light"
          href="{% url 'activities:list' %}"
        >
          返回列表
        </a>
      </div>
    </div>
  </form>
    
</section>

<div class="modal" id="image-modal">
  <div class="modal-background"></div>
  <div class="modal-content">
    <p class="image">
      <img class="modal-image">
    </p>
  </div>
  <button class="modal-close is-large" aria-label="close"></button>
</div>
{% endblock %}

activities/templates/activities/detail.html
{% extends 'common/base.html' %}

{% load static %}
{% block title %}
投票详情
{% endblock %}
{% block static %}
<link rel="stylesheet" href="{% static "activities/css/common.css" %}" />
<link rel="stylesheet" href="{% static "activities/css/detail.css" %}" />
<script src="{% static "activities/js/common.js" %}"></script>
<script>
  var remaining_vote_num = {{remaining_vote_num}};
</script>
<script src="{% static "activities/js/detail.js" %}"></script>
{% endblock %}

{% block content %}
<section class="container">
  <nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'activities:list' %}">投票</a></li>
      <li class="is-active"><a href="#" aria-current="page">投票详情</a></li>
    </ul>
  </nav>
</section>
<section class="hero container">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        {{activity.title}}
      </h1>
      <h2 class="subtitle">
        每位投票者最多可投{{activity.vote_num_per_user}}票</br>
        投票截止日期：{{activity.end_datetime|date:"Y-m-d H:i:s"}}
      </h2>

    </div>
  </div>
  {% with user_id=request.user.id %}
  <form
    class="vote-form"
    method="post"
    enctype="multipart/form-data"
    action="{% url 'activities:vote' %}"
  >
    {% csrf_token %}
    <input type="hidden" name="activity_id" value="{{activity.id}}" />
    <div class="columns is-multiline option-container">
      {% for option in options %}
      <div class="column is-one-third">
        <div class="card">
          <header class="card-header">
            <p class="card-header-title">
              选项
              {% if activity.is_finished %}
              ({{option.vote_set.count}})
              {% endif %}
            </p>
            {% if user_id in option.get_voters %}
            <div class="ribbon ribbon-top-right">
              <span>已投票</span>
            </div>
            {% elif not activity.is_finished and user_id not in activity.vote_done_users %}
            <label class="checkbox">
              <input type="checkbox" name="option_id" value="{{option.id}}" />
            </label>
            {% endif %}
          </header>
          <div class="card-image">
            <figure class="image is-4by3 image-box">
              <a href="{{option.image.url}}" target="_blank" title="预览图片">
                <img class="option-image" src="{{option.image.url}}" />
              </a>
              <!--
              <div class="actions is-hidden">
                <a
                  class="button is-primary is-light preview-image"
                  title="预览图片"
                >
                  <span class="icon">
                    <i class="fa fa-eye" aria-hidden="true"></i>
                  </span>
                </a>
              </div>
              -->
            </figure>
          </div>
          <div class="card-content">
            <div class="content">
              {{option.content}}
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="field is-grouped is-justified-center button-box">
      {% if not activity.is_finished and user_id not in activity.vote_done_users %}
      <div class="control">
        <button class="button is-link">投票</button>
      </div>
      {% endif %}
      <div class="control">
        <a
          type="button"
          class="button is-link is-light"
          href="{% url 'activities:list' %}"
        >
          返回列表
        </a>
      </div>
    </div>
  </form>
  {% endwith %}
</section>

<div class="modal" id="image-modal">
  <div class="modal-background"></div>
  <div class="modal-content">
    <p class="image">
      <img class="modal-image">
    </p>
  </div>
  <button class="modal-close is-large" aria-label="close"></button>
</div>
{% endblock %}

activities/templates/activities/list.html
{% extends 'common/base.html' %}

{% load static %}
{% block title %}
投票活动列表
{% endblock %}
{% block static %}
<link rel="stylesheet" href="{% static "common/css/bulma-calendar.min.css" %}" />
<link rel="stylesheet" href="{% static "activities/css/list.css" %}" />
<script src="{% static "common/js/infinite-scroll.pkgd.min.js" %}"></script>
<script src="{% static "activities/js/list.js" %}"></script>
<script>
  var pageCount = {{ activities.paginator.num_pages }};
</script>
{% endblock %}

{% block content %}
<div class="tabs is-centered">
  <input name="status" type="hidden" value="{{ request.GET.status }}" />
  <ul>
    {% with status=request.GET.status %}
    <li class="{% if not status or status == '0' %}is-active{% endif %}">
      <a href="{% url 'activities:list' %}?status=0">进行中</a>
    </li>
    <li class="{% if status == '1' %}is-active{% endif %}">
      <a href="{% url 'activities:list' %}?status=1">已结束</a>
    </li>
    {% endwith %}
  </ul>
</div>
<section class="container">
  {% if request.user.can_create_vote %}
  <nav class="level">
    <div class="level-left"></div>
    <div class="level-right">
      <div class="level-item">
        <a class="button is-info" href="{% url 'activities:create' %}">
          <strong>发起投票</strong>
        </a>
      </div>
    </div>
  </nav>
  {% endif %}
  <div class="columns activities is-multiline">
    {% for activity in activities %}
    <div class="column is-one-third activity-item">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title">
            投票
          </p>
          <a href="#" class="card-header-icon" aria-label="more options">
            <span class="icon">
              <i class="fa fa-angle-down" aria-hidden="true"></i>
            </span>
          </a>
        </header>
        <div class="card-content">
          <div class="content">
            {{activity.title}}
          </div>
          <div>
            投票截止日期：{{activity.end_datetime|date:"Y-m-d H:i:s"}}
          </div>
        </div>
        <footer class="card-footer">
          <a 
            href="{% url 'activities:detail' activity.id %}"
            class="card-footer-item"
          >
            {% if activity.is_finished or request.user.id in activity.vote_done_users %}
            查看
            {% elif request.user.id in activity.voted_users %}
            继续投票
            {% else %}
            参与投票
            {% endif %}
          </a>
        </footer>
      </div>
    </div>
    {% empty %}
    <div class="container no-data-box">
      <div class="is-flex no-data">
        <img src="{% static "common/img/empty.png" %}" />
      </div>
      <div class="is-flex no-data">
        <div>暂无投票活动</div>
      </div>
    </div>
    {% endfor %}
  </div>
</section>
<div class="page-load-status
            {% if activities.paginator.num_pages < 2 %}
            is-visible
            {% endif %}"
>
  {% if activities.paginator.num_pages > 1 %}
  <div class="loader-ellips infinite-scroll-request">
    <span class="loader-ellips__dot"></span>
    <span class="loader-ellips__dot"></span>
    <span class="loader-ellips__dot"></span>
    <span class="loader-ellips__dot"></span>
  </div>
  {% endif %}
  <p class="infinite-scroll-last"></p>
</div>
{% endblock %}